laser_: "/transformed_scan"
odom_: "/odom"
bumper_f_: "/Hero/base_f_bumper_sensor"
bumper_b_: "/Hero/base_b_bumper_sensor"
base_ref_: "/cmd_vel"
open_door_: "/Hero/open_door"
speak_: "/Hero/text_to_speech/input"
play_: "/Hero/text_to_speech/file"